"""
LexMatter AI — Layer 5: Analysis Layer ORM Models
Models: EvidenceMapping, Finding, EvidenceGap, ResearchIssue
"""

from datetime import datetime
from typing import List, Optional
from sqlalchemy import (
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship as orm_relationship

from backend.app.core.db import Base
from backend.app.core.id_generator import (
    PREFIX_EVIDENCE_GAP,
    PREFIX_EVIDENCE_MAPPING,
    PREFIX_FINDING,
    PREFIX_RESEARCH_ISSUE,
    generate_id,
)


class EvidenceMapping(Base):
    """Formal evidentiary connection between a SourceAssertion and a RequirementVersion."""
    __tablename__ = "evidence_mappings"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: generate_id(PREFIX_EVIDENCE_MAPPING),
    )
    matter_id: Mapped[str] = mapped_column(String(36), ForeignKey("matters.id", ondelete="CASCADE"), nullable=False)
    source_assertion_id: Mapped[str] = mapped_column(String(36), ForeignKey("source_assertions.id", ondelete="CASCADE"), nullable=False)
    requirement_version_id: Mapped[str] = mapped_column(String(36), ForeignKey("requirement_versions.id", ondelete="RESTRICT"), nullable=False)
    relationship: Mapped[str] = mapped_column(String(50), nullable=False)
    target_dimension: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    relevance_score: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    analysis_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(nullable=False, default=datetime.utcnow)

    # Relationships
    matter: Mapped["Matter"] = orm_relationship("Matter", back_populates="evidence_mappings")
    source_assertion: Mapped["SourceAssertion"] = orm_relationship("SourceAssertion", back_populates="evidence_mappings")
    requirement_version: Mapped["RequirementVersion"] = orm_relationship("RequirementVersion", back_populates="evidence_mappings")

    __table_args__ = (
        Index("idx_evm_lookup", "matter_id", "requirement_version_id", "relationship"),
        {"extend_existing": True},
    )


class Finding(Base):
    """Analytical conclusion, risk assessment, or consistency flag generated by AI agents."""
    __tablename__ = "findings"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: generate_id(PREFIX_FINDING),
    )
    matter_id: Mapped[str] = mapped_column(String(36), ForeignKey("matters.id", ondelete="CASCADE"), nullable=False)
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="MEDIUM")
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    supporting_span_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    impacted_requirement_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="PENDING_REVIEW")

    created_at: Mapped[datetime] = mapped_column(nullable=False, default=datetime.utcnow)

    # Relationships
    matter: Mapped["Matter"] = orm_relationship("Matter", back_populates="findings")

    __table_args__ = (
        Index("idx_findings_matter_status", "matter_id", "status", "severity"),
        Index("idx_findings_spans_gin", "supporting_span_ids", postgresql_using="gin"),
        {"extend_existing": True},
    )


class EvidenceGap(Base):
    """Identifies missing or weakly supported requirement dimensions in the case package."""
    __tablename__ = "evidence_gaps"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: generate_id(PREFIX_EVIDENCE_GAP),
    )
    matter_id: Mapped[str] = mapped_column(String(36), ForeignKey("matters.id", ondelete="CASCADE"), nullable=False)
    requirement_version_id: Mapped[str] = mapped_column(String(36), ForeignKey("requirement_versions.id", ondelete="RESTRICT"), nullable=False)
    dimension: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="POTENTIAL_GAP")
    observation: Mapped[str] = mapped_column(Text, nullable=False)
    searched_document_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    created_at: Mapped[datetime] = mapped_column(nullable=False, default=datetime.utcnow)

    # Relationships
    matter: Mapped["Matter"] = orm_relationship("Matter", back_populates="evidence_gaps")
    requirement_version: Mapped["RequirementVersion"] = orm_relationship("RequirementVersion", back_populates="evidence_gaps")
    research_issues: Mapped[List["ResearchIssue"]] = orm_relationship("ResearchIssue", back_populates="evidence_gap")

    __table_args__ = (
        Index("idx_gaps_status", "matter_id", "status"),
        {"extend_existing": True},
    )


class ResearchIssue(Base):
    """Structured legal query generated for the authoritative Research Agent."""
    __tablename__ = "research_issues"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: generate_id(PREFIX_RESEARCH_ISSUE),
    )
    matter_id: Mapped[str] = mapped_column(String(36), ForeignKey("matters.id", ondelete="CASCADE"), nullable=False)
    triggered_by_gap_id: Mapped[Optional[str]] = mapped_column(String(36), ForeignKey("evidence_gaps.id", ondelete="SET NULL"), nullable=True)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    preferred_authorities: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="OPEN")
    synthesis_result: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    cited_authority_ids: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    created_at: Mapped[datetime] = mapped_column(nullable=False, default=datetime.utcnow)

    # Relationships
    matter: Mapped["Matter"] = orm_relationship("Matter", back_populates="research_issues")
    evidence_gap: Mapped[Optional["EvidenceGap"]] = orm_relationship("EvidenceGap", back_populates="research_issues")

    __table_args__ = (
        Index("idx_riss_status", "matter_id", "status"),
        {"extend_existing": True},
    )
