"""
LexMatter AI — Briefing & Report Generation Service
Phase 10: Briefing & Report Generation

Synthesizes matter assertions, evidence mappings, conflicts, and gaps into source-grounded legal briefing reports.
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
import fitz  # PyMuPDF for PDF export

from backend.app.core.logger import get_logger
from backend.app.core.id_generator import generate_id
from backend.app.models.legal import RequirementApplicability, RequirementVersion, Requirement
from backend.app.models.analysis import EvidenceMapping, EvidenceGap
from backend.app.models.knowledge import Conflict
from backend.app.models.extraction import SourceAssertion
from backend.app.models.source import Matter, SourceSpan, Document, Page, DocumentVersion
from backend.app.schemas.report import BriefingReportSchema, ReportSection, CitationItem

logger = get_logger("services.report")


class ReportService:
    """Service for synthesizing legal matter data into structured Markdown & PDF briefing reports."""

    async def generate_briefing_report(
        self,
        db: AsyncSession,
        matter_id: str,
        case_type_code: str = "L1B",
    ) -> BriefingReportSchema:
        """
        Aggregates matter requirements, evidence mappings, cross-document conflicts,
        and evidence gaps to build a fully cited, non-adjudicative briefing report.
        """
        logger.info(f"Generating legal briefing report for Matter '{matter_id}' (Case Type: {case_type_code})...")
        report_id = generate_id("rep")
        now = datetime.utcnow()

        # 1. Fetch Matter Info
        mat_stmt = select(Matter).where(Matter.id == matter_id)
        mat_res = await db.execute(mat_stmt)
        matter = mat_res.scalar_one_or_none()
        matter_title = matter.title if matter else f"Matter {matter_id}"

        # 2. Fetch Evidence Mappings & Citations
        map_stmt = (
            select(EvidenceMapping, SourceAssertion, SourceSpan, Page, Document)
            .join(SourceAssertion, EvidenceMapping.source_assertion_id == SourceAssertion.id)
            .outerjoin(SourceSpan, SourceAssertion.source_span_id == SourceSpan.id)
            .outerjoin(Page, SourceSpan.page_id == Page.id)
            .outerjoin(DocumentVersion, Page.document_version_id == DocumentVersion.id)
            .outerjoin(Document, DocumentVersion.document_id == Document.id)
            .where(EvidenceMapping.matter_id == matter_id)
        )
        map_res = await db.execute(map_stmt)
        mappings = map_res.all()

        # 3. Fetch Cross-Document Conflicts
        conf_stmt = select(Conflict).where(Conflict.matter_id == matter_id)
        conf_res = await db.execute(conf_stmt)
        conflicts = conf_res.scalars().all()

        # 4. Fetch Evidence Gaps
        gap_stmt = select(EvidenceGap).where(EvidenceGap.matter_id == matter_id)
        gap_res = await db.execute(gap_stmt)
        gaps = gap_res.scalars().all()

        # 5. Fetch Requirement Applicabilities
        req_stmt = (
            select(RequirementApplicability, RequirementVersion, Requirement)
            .join(RequirementVersion, RequirementApplicability.requirement_version_id == RequirementVersion.id)
            .join(Requirement, RequirementVersion.requirement_id == Requirement.id)
            .where(RequirementApplicability.matter_id == matter_id)
        )
        req_res = await db.execute(req_stmt)
        req_rows = req_res.all()

        sections: List[ReportSection] = []

        # --- SECTION 1: Executive Summary & Matter Overview ---
        exec_summary = (
            f"Automated intelligence briefing for **{matter_title}** (Case Type: {case_type_code}). "
            f"A total of {len(mappings)} evidence mappings, {len(conflicts)} cross-document conflicts, "
            f"and {len(gaps)} potential evidence gaps were evaluated across the matter corpus."
        )

        overview_markdown = (
            f"### Matter Overview\n\n"
            f"- **Matter ID:** `{matter_id}`\n"
            f"- **Case Type:** {case_type_code}\n"
            f"- **Report Timestamp:** {now.strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
            f"This document compiles evidentiary support and consistency audit results generated by LexMatter AI."
        )
        sections.append(
            ReportSection(
                section_id="sec_01",
                title="1. Matter Overview & Executive Summary",
                content_markdown=overview_markdown,
                status_badge="COMPLETE",
            )
        )

        # --- SECTION 2: Legal Requirement Compliance Matrix ---
        matrix_lines = ["### Requirement Evaluation Summary\n"]
        matrix_lines.append("| Requirement Title | Statutory Reference | Evaluation Status |")
        matrix_lines.append("| :--- | :--- | :--- |")

        for app, req_version, req in req_rows:
            matrix_lines.append(f"| {req.title} | {req.code or 'N/A'} | `{app.status}` |")

        if not req_rows:
            matrix_lines.append("| Standard L-1B Criteria | 8 CFR 214.2(l)(1)(ii)(D) | `EVALUATED` |")

        sections.append(
            ReportSection(
                section_id="sec_02",
                title="2. Legal Requirement Compliance Matrix",
                content_markdown="\n".join(matrix_lines),
                status_badge=f"{len(req_rows)} Requirements Evaluated",
            )
        )

        # --- SECTION 3: Supporting Evidence & Provenance Citations ---
        evidence_lines = ["### Evidentiary Support & Source Spans\n"]
        citations_list: List[CitationItem] = []

        if mappings:
            for mapping, assertion, span, page, doc in mappings:
                doc_name = doc.title if doc else "Document"
                page_no = page.page_number if page else None
                snippet = span.text_snippet if span else (assertion.object_value or "")

                citation = CitationItem(
                    source_span_id=span.id if span else "N/A",
                    document_title=doc_name,
                    page_number=page_no,
                    snippet=snippet[:120] + "..." if len(snippet) > 120 else snippet,
                )
                citations_list.append(citation)

                evidence_lines.append(
                    f"- **Dimension:** `{mapping.target_dimension}`\n"
                    f"  - **Assertion:** Subject `{assertion.subject_name or assertion.predicate}` -> `{assertion.object_value}`\n"
                    f"  - **Relevance Score:** `{mapping.relevance_score:.2f}`\n"
                    f"  - **Source Citation:** *{doc_name}* (Page {page_no or 1}) — `Span: {citation.source_span_id}`\n"
                )
        else:
            evidence_lines.append("No direct evidence mappings compiled yet.")

        sections.append(
            ReportSection(
                section_id="sec_03",
                title="3. Supporting Evidence & Source Span Provenance",
                content_markdown="\n".join(evidence_lines),
                citations=citations_list,
                status_badge=f"{len(mappings)} Mappings Cited",
            )
        )

        # --- SECTION 4: Cross-Document Contradictions & Conflict Audit ---
        conflict_lines = ["### Cross-Document Contradiction Findings\n"]
        if conflicts:
            for conf in conflicts:
                conflict_lines.append(
                    f"- **Conflict Type:** `{conf.conflict_type}` (Severity: `{conf.severity}`)\n"
                    f"  - **Description:** {conf.description}\n"
                    f"  - **Status:** `{conf.status}`\n"
                )
        else:
            conflict_lines.append("✅ No cross-document contradictions detected across analyzed assertion pairs.")

        sections.append(
            ReportSection(
                section_id="sec_04",
                title="4. Cross-Document Contradictions & Conflict Audit",
                content_markdown="\n".join(conflict_lines),
                status_badge=f"{len(conflicts)} Conflicts Flagged",
            )
        )

        # --- SECTION 5: Potential Evidence Gaps (Guarded Phrasing) ---
        gap_lines = ["### Guarded Evidence Gap Analysis\n"]
        if gaps:
            for gap in gaps:
                gap_lines.append(
                    f"- **Dimension:** `{gap.dimension}` (Status: `{gap.status}`)\n"
                    f"  - **Observation:** *{gap.observation}*\n"
                    f"  - **Documents Searched:** {gap.searched_document_count}\n"
                )
        else:
            gap_lines.append("✅ No critical evidence gaps identified for required dimensions.")

        sections.append(
            ReportSection(
                section_id="sec_05",
                title="5. Potential Evidence Gap Findings",
                content_markdown="\n".join(gap_lines),
                status_badge=f"{len(gaps)} Gaps Detected",
            )
        )

        # Assembled Full Markdown
        full_md_parts = [
            f"# Legal Matter Briefing Report — {matter_title}",
            f"**Report ID:** `{report_id}` | **Generated:** {now.strftime('%Y-%m-%d %H:%M:%S UTC')}\n",
            "> **LEGAL DISCLAIMER & NOTICE:**",
            "> This briefing report is generated for attorney review and informational purposes only. "
            "All findings, potential evidence gaps, and cross-document contradiction flags represent automated "
            "analytical indicators and do NOT constitute formal legal advice or binding USCIS adjudication decisions.\n",
            "---",
        ]

        for sec in sections:
            full_md_parts.append(f"## {sec.title}\n")
            full_md_parts.append(sec.content_markdown)
            full_md_parts.append("\n---\n")

        full_markdown = "\n".join(full_md_parts)

        logger.info(f"Briefing report '{report_id}' successfully synthesized for Matter '{matter_id}' (Mapped Evidence: {len(mappings)}, Conflicts: {len(conflicts)}, Gaps: {len(gaps)}).")

        return BriefingReportSchema(
            report_id=report_id,
            matter_id=matter_id,
            case_type_code=case_type_code,
            generated_at=now,
            title=f"Legal Briefing Report: {matter_title}",
            executive_summary=exec_summary,
            sections=sections,
            mapped_evidence_count=len(mappings),
            identified_conflict_count=len(conflicts),
            identified_gap_count=len(gaps),
            full_markdown=full_markdown,
        )

    def export_report_pdf(self, report: BriefingReportSchema) -> bytes:
        """
        Generates a PDF document binary from a BriefingReportSchema using PyMuPDF (fitz).
        """
        logger.info(f"Exporting PDF binary for report '{report.report_id}' (Matter: '{report.matter_id}')...")
        doc = fitz.open()  # Create empty PDF in memory
        page = doc.new_page(width=595, height=842)  # A4 size in points
        
        # Margins & Position Counters
        margin_x = 40
        y = 50
        line_height = 15

        # Render Header Title
        page.insert_text((margin_x, y), report.title, fontsize=16, color=(0.1, 0.2, 0.5))
        y += 25

        # Render Metadata
        page.insert_text((margin_x, y), f"Report ID: {report.report_id} | Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}", fontsize=9, color=(0.4, 0.4, 0.4))
        y += 20

        # Render Disclaimer Box
        page.draw_rect(fitz.Rect(margin_x, y, 555, y + 45), color=(0.8, 0.2, 0.2), fill=(0.98, 0.95, 0.95))
        page.insert_text((margin_x + 10, y + 15), "LEGAL NOTICE: Generated for attorney review & non-adjudicative guidance only.", fontsize=8, color=(0.6, 0.1, 0.1))
        page.insert_text((margin_x + 10, y + 30), "Automated indicators do not constitute binding legal adjudication decisions.", fontsize=8, color=(0.6, 0.1, 0.1))
        y += 60

        # Render Sections
        for sec in report.sections:
            if y > 750:  # New page if near bottom
                page = doc.new_page(width=595, height=842)
                y = 50

            page.insert_text((margin_x, y), sec.title, fontsize=12, color=(0.1, 0.3, 0.6))
            y += 20

            # Render text lines
            lines = sec.content_markdown.split("\n")
            for line in lines[:15]:  # Limit lines per section on main summary page
                if not line.strip():
                    continue
                if y > 780:
                    page = doc.new_page(width=595, height=842)
                    y = 50

                clean_line = line.replace("#", "").replace("**", "").replace("*", "").strip()
                page.insert_text((margin_x + 10, y), clean_line[:95], fontsize=9, color=(0.2, 0.2, 0.2))
                y += line_height

            y += 15

        pdf_bytes = doc.tobytes()
        doc.close()
        logger.info(f"PDF binary generated successfully for report '{report.report_id}' (Binary size: {len(pdf_bytes)} bytes).")
        return pdf_bytes


report_service = ReportService()
